[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  MONGODB_URI = "your-mongodb-uri"
  JWT_SECRET = "your-jwt-secret"
  NODE_ENV = "production"

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs" 